### ISSUE TITLE
Can't call builder.trigger with nil second param in new MM

### ISSUE THREAD

**Issue by cpence** [follmann/middleman-favicon-maker#36]
Doing so gives the following contract violation:

```
/Users/pence/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.12.0/lib/contracts.rb:48:in `block in <class:Contract>': Contract violation for argument 2 of 3: (ParamContractError)
        Expected: (String or Pathname),
        Actual: nil
        Value guarded in: Middleman::Builder::trigger
        With Contract: Symbol, Or, Maybe => Any
```

Looks like it's coming from [right here.](https://github.com/follmann/middleman-favicon-maker/blob/master/lib/middleman-favicon-maker/extension.rb#L42)

From [the original method,](https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/builder.rb#L290) it looks like you should be passing in the file path as the second parameter, and maybe nothing at all for the third parameter. (It looks optional, given the way that other MM methods call Builder#trigger.)

**Comment by follmann** [comment]
Just released version 4.0.2 that includes the fix. Thanks for reporting!
